# Generated by Django 5.1.2 on 2024-12-24 16:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_book_cover_conspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to=api.models.user_directory_path),
        ),
    ]
