# Generated by Django 5.1.2 on 2024-12-25 16:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='static/img/covers/default.jpg', upload_to=api.models.user_directory_path),
        ),
    ]
